### PR TITLE
Fix test copy/paste typo

### PR DESCRIPTION
**Pull request by ejrgilbert**

### CODE REVIEW

**Comment by tlively** [comment]
Looks right, but curious that the tests weren't previously failing.

**Comment by jakobkummerow** [comment]
> curious that the tests weren't previously failing.

`i31.get_s` and `i31.get_u` both trap on `(ref.null i31)`, so this doesn't affect test results.

**Review by jakobkummerow — APPROVED** [review]
LGTM

**Comment by tlively** [comment]
Ah, I misread and though that this function was used to test non-null cases.

**Pull request merged**
