### PR TITLE
Add a test for malformed mutability in array types

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by rossberg** [comment]
Makes sense, although I'd prefer to put this into a new gc/binary-gc.wast, analogous to the binary tests for the main language.

**Comment by fitzgen** [comment]
Will split it out into `binary-gc.wast`.

**Comment by fitzgen** [comment]
This seems to be failing CI but I can't glean any useful information from the logs:

https://github.com/WebAssembly/gc/actions/runs/5060174415/jobs/9082705163?pr=380#step:7:56

```
======================================================================
FAIL: test binary-gc.wast (__main__.RunTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/gc/gc/interpreter/../test/core/run.py", line 120, in <lambda>
    setattr(RunTests, testName, lambda self, file=fileName: self._runTestFile(file))
  File "/home/runner/work/gc/gc/interpreter/../test/core/run.py", line 82, in _runTestFile
    self._runCommand(('%s "%s"') % (wasmCommand, inputPath), logPath, expectedExitCode)
  File "/home/runner/work/gc/gc/interpreter/../test/core/run.py", line 52, in _runCommand
    self.assertEqual(expectedExitCode, exitCode, "failed with exit code %i (expected %i) for %s" % (exitCode, expectedExitCode, command))
AssertionError: 0 != 1 : failed with exit code 1 (expected 0) for /home/runner/work/gc/gc/interpreter/wasm "/home/runner/work/gc/gc/test/core/gc/binary-gc.wast"
```

Any idea what is going on?

**Comment by fitzgen** [comment]
Ah, if I run the test directly, rather than through the full test suite, I get this:

```
Result: "integer representation too long"
Expect: "malformed mutability"
test/core/gc/binary-gc.wast:1.1-12.2: assertion failure: wrong decoding error
```

Looking into it.

**Comment by fitzgen** [comment]
Should be fixed now.

**Pull request merged**
