### PR TITLE
Remove the immediate from array.len in binary format

### PR DESCRIPTION
**Pull request by titzer**
This addresses a small TODO in the binary encoding/decoding of the reference interpreter.

### CODE REVIEW

**Comment by tlively** [comment]
lgtm fwiw

**Review by rossberg — APPROVED** [review]
LGTM, but FWIW, I left this in intentionally to remain compatible with V8 until they decide to update their implementation. Has that happened? Otherwise, e.g. Wob&Waml will break.

**Comment by manoskouk** [comment]
We have not updated the V8 implementation yet. We are planning to implement breaking changes when other discussions are also resolved (e.g. #274).

**Comment by titzer** [comment]
It's already a breaking change, because the reference interpreter is using a zero byte now, and V8 would be interpreting that as a type index.

@manoskouk This should be a very small number of lines to change in V8. Any chance we can go ahead with it, without blocking on another discussion?

**Comment by manoskouk** [comment]
In V8, we [accept but ignore](https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit#bookmark=id.m372kw3q8qfn) the type index.
This is compatible with the code containing a zero byte instead. If we remove it completely, it will break our partners' compiled benchmarks.
That said, we understand that the online spec's changes cannot always be synced to ours; this is why we maintain a separate spec for V8's implementation. So feel free to merge this change, just please be aware that our implementation will adopt it later.

**Comment by titzer** [comment]
Ok, thanks for the explanation.

We'll have to start breaking binary compatibility, either little by little or all at once. As this is a small one, I think we should land it, but I'll let @rossberg make the call, since he'll have to update Wob and Waml.

**Comment by rossberg** [comment]
The reference interpreter currently also decodes but ignores the type index.

The problem with Wob and Waml isn't that I have to update them, but that their test suite runs on both the reference interpreter and V8. So if they diverge, breakage is unavoidable.

Do you have a pressing need to land this now?

**Pull request merged**
