### PR TITLE
Add a test for #516 to the test suite

### PR DESCRIPTION
**Pull request by fitzgen**
r? @rossberg

### CODE REVIEW

**Review by rossberg — COMMENTED** [review]
Thanks! But since the issue it tests actually is the typing of br_on_null, I think it would be more appropriate to add  this test to br_on_null.wast.

**Comment by fitzgen** [comment]
There isn't a `br_on_null.wast` in the `gc` directory. Should I create one?

**Comment by rossberg** [comment]
It's in the main directory. But you'll need to modify the example to avoid the use of GC features (which should be inessential to the issue). E.g. with some use of subtyping that works with just the funcref proposal.

**Comment by fitzgen** [comment]
@rossberg rewrote it to use `(ref null $ty)` and `funcref` instead of `structref` and `anyref` and moved the test into `br_on_null.wast`.

**Review by rossberg — APPROVED** [review]
Thanks!

**Pull request merged**
